version: '3.8'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=jobs
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - db:/var/lib/postgresql/data
  meili:
    image: getmeili/meilisearch
    volumes:
      - meili:/var/lib/meili_data
    ports:
      - '7700:7700'
volumes:
  # db:
  #   driver: local
  meili:
    driver: local
